language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_unit/ framework/app/libraries/li3_unit
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_unit

script: ../../../libraries/lithium/console/li3 test tests